# Generated by Django 3.2.4 on 2021-06-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_items',
            old_name='todo',
            new_name='todo_name',
        ),
    ]
